services:
  - name: backup-chowmate-db
    type: cron
    schedule: "0 3 * * *"
    region: oregon
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dpg-d44gv4ripnbc73ftlfog-a
          property: connectionString
      - key: AWS_REGION
        sync: false 
      - key: S3_BUCKET_NAME
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: POSTGRES_VERSION
        sync: false
      - key: ALPINE_VERSION
        sync: false
